### ISSUE TITLE
'Applozic/Applozic.h' file not found

### ISSUE THREAD

**Issue by 12jadu34** [AppLozic/Applozic-React-Native-Chat-Messaging-SDK#9]
I have added all the code as described in steps... But I am getting this error due to which I am not able to run on ios.

**Comment by murtraja** [comment]
same here. @12jadu34, did you find any solutions?

**Comment by murtraja** [comment]
even the sample throws this error

**Comment by reytum** [comment]
@12jadu34 @murtraja The pod has not installed. Open the ios/YourAPp.xcworkspace in xcode and check the Pod file. If it does not have entry for Applozic then you need to run the `pod install` command in ios folder from terminal.

**Comment by murtraja** [comment]
@reytum thanks for the quick response, for the sample, as well as for my app, I am getting the exact same error now:
`no such file or directory: /Users/user/Library/Developer/Xcode/DerivedData/ApplozicSample-gyubntfjlpnfyvgfabnpoojugphu/Build/Products/Debug-iphonesimulator/libRNApplozicChat.a`

`no such file or directory: '/Users/user/Library/Developer/Xcode/DerivedData/wishbook-gusdqtxielzcwxeqprulikbieyku/Build/Products/Debug-iphonesimulator/libRNApplozicChat.a`

I have cleaned my project countless times and have deleted the DerivedData folder a trillion times now. Any help will be greatly appreciated given that I am stuck with this since yesterday

**Comment by murtraja** [comment]
@reytum got the sample working, had to remove libRNApplozicChat.a from linked binaries section

**Comment by Sunilkumarr** [comment]
@murtraja Thanks for pointing out. This will help 👍

**Comment by vaibsshukla** [comment]
@murtraja  it didn't helped

**Comment by murtraja** [comment]
@vaibsshukla I am off the project now, wish I could've helped you. :(
